const setting_json = {
  "app_access_toggle": true,
  "updatebycustomer_toggle": true,
  "reorder_toggle": true,
  "sidebar_menu_size": 15,
  "sidebar_heading_size": 33,
  "sidebar_background": "#fffff",
  "sidebar_customer_name": "#000",
  "sidebar_menu_background": "#fffff",
  "sidebar_menu_text": "#000",
  "sidebar_menu_active": "#000",
  "sidebar_icon": "#00ffba",
  "sidebar_menu_text_hover": "#000",
  "main_content_text_size":20,
  "main_content_heading_size":30,
  "main_content_background": "#fffff",
  "main_content_foreground": "#fffff",
  "main_content_primary": "#000",
  "main_content_heading": "#000",
  "main_content_order_item_back": "#fff",
  "main_content_text": "#000",
  "main_content_foreground_text": "#000",
  "custom_css": ""
}
export default setting_json