# fly.toml file generated for customer-dashboard-pro on 2022-11-15T14:18:48+05:30

app = "customer-dashboard-pro"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8080"
HOST = "https://customer-dashboard-pro.fly.dev"
SHOPIFY_API_KEY = "ee5b2c78feec2e8755c58cc3056c58f6"
SHOPIFY_API_SECRET="3eb78dafb8406d01e4fb312d5d14e13c"
SCOPES = "read_customers,read_orders,read_locales,read_content,read_themes,write_themes,write_customers"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
