const setting_json = {
  "app_access_toggle": true,
  "updatebycustomer_toggle": true,
  "reorder_toggle": true,
  "sidebar_menu_size": 15,
  "sidebar_heading_size": 33,
  "sidebar_border":"#e5e5e5",
  "sidebar_customer_name": "#000",
  "sidebar_menu_header_background": "#fff",
  "sidebar_menu_background": "#fff",
  "sidebar_menu_text": "#000",
  "sidebar_menu_active": "#000",
  "sidebar_menu_active_text": "#fff",
  "sidebar_menu_hover": "#000",
  "sidebar_menu_text_hover": "#fff",
  "main_content_text_size":16,
  "main_content_heading_size":30,
  "main_content_primary": "#000",
  "main_content_primary_text": "#fff",
  "main_content_primary_hover": "#fff",
  "main_content_background": "#fff",
  "main_content_foreground": "#fff",
  "main_content_foreground_text": "#000",
  "main_content_text": "#000",
  "main_content_heading": "#000",
  "main_content_label": "#000",
  "custom_css": ""
}
export default setting_json